### ISSUE TITLE
Change serialNumber

### ISSUE THREAD

**Issue by arkadicolson** [ztalbot2000/homebridge-cmd4#119]
Hi

One short question. I changed the serialNumber after initial install but it doesn't change in the home app. Is this cached somewhere? Is there a way to change this somehow without deleting the device? I'm asking this because the controller app is reporting this conflict when making backups of the config.

Thanks!

**Comment by ztalbot2000** [comment]
Hi,

  Homebridge would probably cache the serial number. I don't know off hand
how to change it without deleting the accessory and then adding it back. I
could look into it later, it's 4:23 AM at the moment.

Ttyl,
John Talbot

**Comment by mitch7391** [comment]
@arkadicolson  I would suggest have suggested to just delete the accessory from the homebridge cache from the UI settings; which sounds like what you want to avoid. Could be worth trying to removing `serialNumber` from your config, save and reboot; then add it back in, save and reboot. This might sort it out and is worth a go.

**Comment by ztalbot2000** [comment]
Hi,

  I was right and so is Mitch. Unfortunately that is the only way; At this
time.
  I say this is the only way now, because I have been working on
Homebridge-UI. It is no way near production ready, but I did try it for the
serialNumber and it allowed me to update it!
  So I will close this as the accepted answer for now is to remove and add
it back. As well there is already an open ticket for the Homebridge-UI
feature.

  Take care,
John Talbot

**Comment by ztalbot2000** [comment]
closed as per last comment.
