### ISSUE TITLE
[Support] After installing and restarting nothing happens

### ISSUE THREAD

**Issue by WaldperlachFabi** [ztalbot2000/homebridge-cmd4#128]
**Describe Your Problem:**
I installed Cm4 and restarted HomeBridge, in Home aren’t demo devices and there are no logs from this plugin. Indent have a config and I didn’t know if I understood the wiki right that if I don’t have a config demo mode is enabled.

**Cmd4 Config:**

```json
I don’t have a config
```

**Environment:**

* **Node.js Version**: v14.17.3
* **NPM Version**: v8.3.0
* **Homebridge Version**: v1.4.0
* **homebridge-cmd4 Version**: v6.1.2
* **Operating System**: Docker
* **Process Supervisor**: Docker

**Comment by ztalbot2000** [comment]
Hi,

There is a default config with the installed plugin,
Most likely /usr/local/lib/node_modules/homebridge-cmd4/Extras/config.json

Ttyl,
John

**Comment by WaldperlachFabi** [comment]
Thank you for your help! Is it possible to add all devices in a „Test-Home“ useing a Bridge? Thank you! Fabi

**Comment by ztalbot2000** [comment]
Hi,

That config.json I pointed you to has all the possible devices

Ttyl,
John

**Comment by WaldperlachFabi** [comment]
Hi, didn’t mean that 😂. I meant this Feature:
![6ED638C7-54C6-410D-9EE3-450D5DC0D23C](https://user-images.githubusercontent.com/80318133/154031988-c72d4cf6-8e3a-46ec-817b-288047207eda.jpeg)
Thank you for your help!

**Comment by ztalbot2000** [comment]
Hi,

It's not looking familiar.  It looks like a homebridge-UI thing.  I'll look.

Ttyl,
John

**Comment by WaldperlachFabi** [comment]
Yeah normally you can then enable this switch [Picture 1] and then you will be able to add a bridge in HomeKit [Picture 2] with all Devices of the Plugin, but if i klick it on this plugin it says that i have to manually configurate it and i don’t know how to. [Picture 3
![576F5B14-3041-4FD0-853C-63AF84DA4881](https://user-images.githubusercontent.com/80318133/154055278-c726611c-de72-4461-b179-83df3c96f640.png)
![E0763471-FBDF-4556-932C-CC9A2287C4C0](https://user-images.githubusercontent.com/80318133/154055291-c7cf48fb-b4d2-4a12-ba50-87428881bfd1.png)
![5286D589-AE24-4528-A578-B2EB108043E4](https://user-images.githubusercontent.com/80318133/154055294-8013a6f0-003a-49ba-896f-37c56b9784ce.png)
]
Thank you for your help!

**Comment by ztalbot2000** [comment]
Hi,

  So I finally had some time to sit down and read carefully your issue and now understand your predicament.

Unfortunately you do have to configure Cmd4 manually.  Cmd4 does not have Homebridge-UI configuration.  There is an open issue on it.

I have seriously tried to get Homebridge-UI working with Cmd4.  The issue is that Cmd4 has so many devices and characteristics to work with, that I have found that creating the config.schéma for it is extremely difficult. I do have a private branch for UI, but it is nowhere near completion and the schéma is over 5000 lines!

So for now, you are going to have to work with the documentation available, and many examples.

Remember Cmd4 was created originally to demonstrate what HomeKit can do if you don't have any accessories at all. It morphed into a tool that you can write shell scripts to control devices either not supported by HomeKit, for features you wish to add or devices you have created yourself.

if I can help you further, just reply to this issue, even though it's closed.

ttyl,
John Talbot
