### ISSUE TITLE
[Feature Request] Adding Shower, TV Stick and Set-Up-Top Box

### ISSUE THREAD

**Issue by WaldperlachFabi** [ztalbot2000/homebridge-cmd4#129]
**Is your feature request related to a problem? Please describe:**
It would be really cool if you could add these devices!

**Describe the solution you'd like:**
Adding these Devices:)

**Describe alternatives you've considered:**

**Additional context:**

![60072B62-8D96-4C22-A21C-A2468F1B94EC](https://user-images.githubusercontent.com/80318133/154258818-be8e7d76-c507-481e-b33f-7f9472f817ec.jpeg)
![4F1DF232-CF41-47EC-9D5D-4DF11F7957CF](https://user-images.githubusercontent.com/80318133/154258926-5e591695-65eb-4e1b-acd1-d00da01ae1e3.jpeg)

**Comment by ztalbot2000** [comment]
Hi,

  Accepted.  There are always new devices being added.  If these are actual devices that Cmd4 can talk to, I'll add them.

ttyl,
John

**Comment by ztalbot2000** [comment]
hi,
  So I did a little research. As defined in
/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Accessory.js

Categories[Categories["TV_SET_TOP_BOX"] = 35] = "TV_SET_TOP_BOX";
 Categories[Categories["TV_STREAMING_STICK"] = 36] = "TV_STREAMING_STICK";

Those are Categories which define how HomeKit will try to display the icon used for the accessory. Cmd4 will allow you to change the category of any accessory as to what is defined in the above.

That being said, there are a few new accessories. I found
  AssetUpdate:
   Assistant:
   AudioStreamManagement:
   Battery:
   CameraOperatingMode:
   CameraRecordingManagement:
   CloudRelay:
   DataStreamTransportManagement:
   NFCAccess:
   SiriEndpoint:
   ThreadTransport

Most of these probably have TLV8 characteristics that are not easy for a user to define.

I'll close this issue as it turns out these are Categories that CMD4 does allow you to use, but I will get around to adding those Accessories I found, unless you need one of those immediately.

Any further issues, just reply to this thread and I will see it.

ttyl,
John Talbot
