### ISSUE TITLE
Testing PS4.sh

### ISSUE THREAD

**Issue by krazyflipj** [ztalbot2000/homebridge-cmd4#16]
Tried setting up PS4. When testing PS4.sh using command line the device on and off code doesn't do anything. However getting the device status works.

**Comment by MrDrache333** [comment]
If you want to Control your Ps4. You first have to get the credentials you can use to authenticate yourself to get control over it.

For most cases, simply run the executable with no arguments. On first run, you will be asked to connect to the "PS4-Waker" Playstation, and to turn on your PS4 and go to the "add devices" screen to get a pin code, and enter that. After that, future executions should just work.

In order to get the credentials, ps4-waker pretends to be another PS4 on your local network, responding to the right broadcasts with the appropriate messages, and simulating the connection handshake that the app makes with a real PS4.

With those in hand, ps4-waker connects to the real PS4 and communicates with the same TCP protocol the app uses to authenticate itself as a connected Device---it will show up as "PS4 Waker" in your device management.

Once registered as a connected Device, it can simply send the correct "wake" packet with the initially-fetched credentials.

In my case I used this Code:
```
#!/bin/bash
#echo $1 $2 $3 $4
if [ "$1" = "Get" ]; then
   # $2 would be the name 'PS4'
   # $3 would be the charactersistic 'On'
   # If you only have one Ps4 in your Network
   state=$(ps4-waker search -t 2000 | grep -c '200 Ok')
   echo "$state"
   exit 0
fi

if [ "$1" = "Set" ]; then
   # $2 would be the name 'PS4'
   # $3 would be the the charactersistic 'On'
   # $4 would be '0' for 'Off', '1' for 'On'

   if [ $4 = true ]; then
      ps4-waker -c <PATH TO CREDENTIALS FILE>
      exit $?
   elif [ $4 = false ]; then
      ps4-waker -c <PATH TO CREDENTIALS FILE> standby
      exit $?
   fi
fi

exit -1
```

**Comment by MrDrache333** [comment]
>I already had ps4-waker setup. I'm able to turn on my ps4 in Terminal. you mention a credentials file? how do I get that?

@krazyflipj Did you read my Reply? 😂

**Comment by krazyflipj** [comment]
Never mind i was able to get it working. I didn't need -c as "ps4-waker" and "ps4-waker standby" on it's own turns on and off respectively.
