### ISSUE TITLE
Try to find a way to get rid of the underscores in device names if possible

### ISSUE THREAD

**Issue by imadphp** [ztalbot2000/homebridge-cmd4#39]
Hi, I have to say I haven't had a close enough look yet to tell if you have, but...

- Did you get a chance to see if you can escape the spaces with backslashes?
- Maybe even extract them afterwards if necessary?
- Is there any way you can replace the spaces with underscores before proceeding to use it in variable names, or anywhere throughout the code?
- Could you maybe introduce a new unique identifier field to use around the rest of the code?

So that the user can still pick the same type of device name they'd choose with regular homekit devices. Because imho the requirement of underscores in device names is a very unfortunate shortcoming, given the fact that the overall features in this project seem very promising.

**Comment by ztalbot2000** [comment]
Hi Imad,

   You have not needed underscores in the device names for a long time.  CMD4 does put double quotes around them when they are exec'd.  I left it there because a lot of people do not understand what happens to scripts or how to parse them when there are spaces involved.

I hope this helps you.

John Talbot.

**Comment by imadphp** [comment]
Okay, many thanks!
