### ISSUE TITLE
[Cmd4] Warning, Retrieving On, expected only one word value for:

### ISSUE THREAD

**Issue by elionth** [ztalbot2000/homebridge-cmd4#46]
Hi,

Thank you for the great effort you put in to build the CMD4 accessory. I would appreciate your feedback on the following error I am receiving.

On and OFF states/ commands execute fine however, the status is not cooperating. At pooling time, I am getting the warning message below and the switch turns OFF

[4/9/2020, 10:49:25 AM] [Cmd4] Warning, Retrieving On, expected only one word value for:TV, using first of:2 packets transmitted, 2 received, 0% packet loss, time 17ms
true

I have tried a lot of iteration to get the status of the device but all give me same results.

   # ps4-waker search | grep -i '200 Ok'
   ## sudo ps4-waker search -d 192.168.50.25 | grep "200 Ok" > null && (echo "true") || (echo "false")
   ### Get current state of MAC address (Is device ON or OFF?)
   ### Ping media server player if it is ON
   ### If the host is up, you should see something like "1 packets transmitted, 1 received, 0% packet loss
   ###    Homebridge-cmd4 will interpret the result of false to be 1 
   ###    and true to be 0 so either 0/1  or true/false can be returned.
   ## 	ping -c 1 -W 1 192.168.1.55 | grep -i '1 received'
   ##		ping -c 2 -W 1 192.168.1.110 | grep -i '2 received'
   ping -c 2 -W 1 192.168.1.110 | grep -i '2 received' > null && (echo "true") || (echo "false")
   ##		ping -c 2 -W 1 192.168.1.110 | grep -i '2 received' > null && (echo "true") || (echo "false")  >> /dev/null
   ## curl -s GET '192.168.1.55' | grep -i '0'

My current switch bash script is as following:

#!/bin/bash

# Notes
# 1) This script is called as defined by the config.json file as:
#    "state_cmd": "bash .homebridge/Cmd4Scripts/PS4.sh"
#    $1 = 'Get'
#    $2 = <Device name>    DO NOT USE SPACES IN DEVICE NAME. It causes problems parsing the command line.
#    $3 = <Characteristic>
#    $4 = <Device option>
#
# 2) For a set of On, the command issued would be:
#    bash $HOME/.homebridge/Cmd4Scripts/PS4.sh Set PS_4 On false
#       or
#    bash $HOME/.homebridge/Cmd4Scripts/PS4.sh Set PS_4 On true
#
# 3) For a Get of On, the command issued would be:
#    bash $HOME/.homebridge/Cmd4Scripts/PS4.sh Get PS_4 On 
#  
#    Homebridge-cmd4 will interpret the result of false to be 1
#    and true to be 0 so either 0/1  or true/false can be returned.

# echo "\$1='$1' \$2='$2' \$3='$3' \$4='$4'"

# This is only here for the first run.
if [ ! -f "/tmp/fileVariableHolder" ]; then
   echo "0" > "/tmp/fileVariableHolder"
fi

if [ "$1" = "Get" ]; then
   # This line is commented out and would be
   # interchangeable with ps4-waker. It is here
   # as an example
   # ps4-waker search | grep -i '200 Ok'
   ping -c 2 -W 1 192.168.1.110 | grep -i '2 received'
   cat /tmp/fileVariableHolder
   rc=$?
   if [ "$rc" = "0" ]; then
      exit 0
   else
      echo "failed"
      exit -1
   fi
fi

.
.
.

Much appreciated

**Comment by ztalbot2000** [comment]
Hi,

   Give me a few minutes.  It has been a while to refresh my memory. From
recollection, polling just gets the status on/or off.  The warning message
is that the ping command is returning more than just he one word. It seems
like it is returning the whole ping response.

I'll get back to you shortly.

**Comment by elionth** [comment]
I tried the following alternatives too:

ping -c 2 -W 1 192.168.1.110 | grep -i '2 received' > null && (echo "true") || (echo "false")
OR
curl -s GET '192.168.1.55' | grep -i '0'


Still getting same message. Thank you

**Comment by ztalbot2000** [comment]
I think the original PS4-Waker came from the original Homebridge-cmd. It
really does not matter. The point of a status check is to ping the device
and to see if it responds.  Every platform may output the results
differently, but typically they are the same.

If I ping my router using: ping -c 2 -W 1 192.168.2.1
I get the result:
PING 192.168.2.1 (192.168.2.1): 56 data bytes

--- 192.168.2.1 ping statistics ---
2 packets transmitted, 2 packets received, 0.0% packet loss, 2 packets out
of wait time
round-trip min/avg/max/stddev = 3.016/3.293/3.571/0.278 ms

In this case the grep would fail, because it is looking for '2 received'
and not '2 packets received'
Your command would then be:
ping -c 2 -W 1 192.168.1.110 | grep -i '2 packets received'

Now you would not send this to Homebridge-CMD4 but the return code of this
as either true, false, 0 or 1.

ping -c 2 -W 1 192.168.1.110 | grep -i '2 packets received'
rc=$?
if [ "$rc" = "0" ]; then
exit 0
else
echo "failed"
exit -1

As with any command. When you break it down into it's parts, you can
explain what it is doing, trying each part from the command line yourself.

I hope this helps.
John Talbot

**Comment by ztalbot2000** [comment]
Hi,

  And by the way.  If the status fails, it would of course go off.

TTFN,
John

**Comment by elionth** [comment]
Seems to be stable now. Thank you.

Tried and works now (should someone else experience same issue):
ping -c 2 -W 1 192.168.1.110 | grep -i '2 packets received'
