### ISSUE TITLE
Homebridge 1.0.4 compatible?

### ISSUE THREAD

**Issue by standre** [ztalbot2000/homebridge-cmd4#50]
Raspberry Pi 3, debian 10.0

I get errors after migrating to homebridge 1.0.4. Most other plugins still work, cmd4 fails when launching any of my scripts, e.g.

```
[06/05/2020, 17:14:28] [Cmd4] getGeneric On function for:Alarm cmd:node /var/homebridge/Cmd4Scripts/Alarm.js Get 'Alarm' 'On' failed.
[06/05/2020, 17:14:28] [Cmd4] { Error: Command failed: node /var/homebridge/Cmd4Scripts/Alarm.js Get 'Alarm' 'On'

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
  killed: true,
  code: null,
  signal: 'SIGTERM',
  cmd:
   'node /var/homebridge/Cmd4Scripts/Alarm.js Get \'Alarm\' \'On\'' }

```

**Comment by ztalbot2000** [comment]
What happens when you run


node /var/homebridge/Cmd4Scripts/Alarm.js Get 'Alarm' 'On'

From the command line?

TTFN,
John Talbot

**Comment by ztalbot2000** [comment]
I did a fresh install and have both seen this failing and working.  It failed the first time and passed all the rest. Possibly because of homebridge taking more time updating its persist and accessory information.  Can you try increasing the timeout?  I'm giving that a try as well.

**Comment by ztalbot2000** [comment]
That seemed to solve my issues.  I changed it from 4000 to 8000. Let me know how yours behaves.

**Comment by standre** [comment]
That’s it: A timeout issue. Although it is now working, the new high latency (of homebridge?) is a drawback. 

Thanks a lot for this hint!

**Comment by ztalbot2000** [comment]
Hi Stan,

  They have done a few funny things.  I'm working on an update. This fix is
one of them.

TTFN,
John

**Comment by ztalbot2000** [comment]
Hi Stan,

   I have not delved into all the details of what they have changed.  They
did move it to typescript, which transpiles to JavaScript. If you look at
the transposed code, you will see that there is a lot of extra stuff that
will slow down a scripted language.  Typescript is great, but is not the
wisest choice for which is essentially an embedded application.  Just
because it is new and shiny, does not make it the right thing to do.
   Unless they resolve this major issue, it would be wiser to go back to
the previous version or maybe fork it to what it was, plus any good changes.

TTFN,
John
