### ISSUE TITLE
No update while in background.

### ISSUE THREAD

**Issue by martinorob** [ztalbot2000/homebridge-cmd4#7]
Hi,
GREAT PLUGIN!!! Thank you!
I have only one problem,
when I update a status, 
for example the status of my door with the 

/usr/local/bin/node /Users/user01/.homebridge/Cmd4Scripts/State.js Set Door TargetPosition 100

it work well but I have to open the Home App on my iPhone to update the door status.

So in this way a never have the alert.

Is my config problem or some bug?

Thank you!!

**Comment by ztalbot2000** [comment]
hi,

   I think that what you are referring to is that the door status does not get pushed to the app.  No HomeKit device actually does this.  HomeBridge would have to be configured to poll the status of door every so often so that its status gets updated.  Even then, HomeKit only gets updated when it is activated by going onto the App anyway.

**Comment by ztalbot2000** [comment]
The solution then is to turn on polling in the config.json file
