### ISSUE TITLE
Documentation Error: malformed sentence

### ISSUE THREAD

**Issue by jsiegenthaler** [ztalbot2000/homebridge-cmd4#94]
**Describe The Bug:**
In this section of the document:
https://github.com/ztalbot2000/homebridge-cmd4#error-cannot-add-a-service-with-the-same-uuid

This paragraph is difficult to understand:

All devices of the same type must have a unique UUID. However this error can occur over restarts when Cmd4 tries to use previous stored configurations that are Cmd4 tries to use. 

The section that appears malformed is highlighted:

However this error can occur over restarts when Cmd4 tries to use previous **stored configurations that are Cmd4 tries to use**.

**Comment by jsiegenthaler** [comment]
Another typo:
https://github.com/ztalbot2000/homebridge-cmd4/blob/master/docs/Developers.md#cmd4-directives

In this sentence, typo highlighted::
A complete list of all Cmd4 directives can be found in the **auoto** generated Cmd4 documentation found at

**Comment by ztalbot2000** [comment]
Totally possible.  I mainly work from an iPad from my hospital bed.  I do
do what I can.

TTFN,
John

**Comment by jsiegenthaler** [comment]
Another possible error (not sure)

Here you have 4 values
https://ztalbot2000.github.io/homebridge-cmd4/autoGenerated/CMD4_AccessoryDescriptions.html#TargetMediaState

Here there are 3 values
https://developers.homebridge.io/#/characteristic/TargetMediaState

I cannot say what is correct, I just noticed the discrepancy...

**Comment by jsiegenthaler** [comment]
> Totally possible. I mainly work from an iPad from my hospital bed. I do do what I can. TTFN, John

Oh dear. Get well soon....

**Comment by ztalbot2000** [comment]
Interesting discrepancy in TargetMediaState.  My auto generated Characteristic and Device tables create an instance of the characteristic and device, using homebridges API. This is in test/CMD4_ACC_TYPE_ENUM.js (Github only). 
line 340:`var characteristic = CMD4_ACC_TYPE_ENUM.properties[accTypeEnumIndex].characteristic;` which is their Characteristic.TargetMediaState.
I then compare their characteristics to what is in CMD4_ACC_TYPE_ENUM. So what I have is correct.
However, If I go to their code, I can also see in node_modules/hap-nodejs/dist/lib/definitions/CharacteristicDefinitions.js for TargetMediaState, they do not list the missing "unknown" state.
Most likely it is because their API's are changing and one is out of sync with the other. Their documentation uses the new API which has not been put into production, but when it does, mine will update as well. I can bring this up with them, if you so wish.
The other documentation errors are being taken care of.

Cmd4 was written to see what HomeKit was all about.  I did not have any devices and being limited as to what I can do, I created something that showed what all the devices could do, without having any of them.  So things are what they are.  I do what I can, when I can.  Thanks for your concern though.

Take care,
John Talbot

**Comment by ztalbot2000** [comment]
So I did some more checking on TargetMediaState.  Homebridge originally had the extra state and I complained about it and others a year ago.  They finally fixed it. However, the Mac I run the  documentation on still has a copy of the old values.  So I can fix this on my end.  Thanks for the keen eye!

take care,
John Talbot

**Comment by jsiegenthaler** [comment]
Thanks. Yes, my eyes see a lot.
